### ISSUE TITLE
大佬，有兴趣搞下在PAAS上部署v2ray吗？

### ISSUE THREAD

**Issue by c21xdx** [xuiv/xuiv.github.io#1]
IBM Cloud 的Cloud Foundry可以部署go的app(免费256MB) 想 把v2ray部署上去，v2ray也是go写的，ibm的app也类似heroku,所以你有兴趣折腾下吗？

**Comment by xuiv** [comment]
c9装tightvncserver,websockify,chromium-browser，novnc，用nginx做好websoket转发，就可以永不休眠了，我还写了一个浏览器自动登录c9的脚本，我现在就是永不休眠。
vnc.hello-xuiv.c9.io
，cloud9马上就会下线了，aws已经发通知了，heroku已经够用了，不想折腾了，墙外其实也没什么，平平淡淡才是真。

2018-05-06 19:03 GMT+08:00 c21xdx <notifications@github.com>:

**Comment by c21xdx** [comment]
仅仅是登录就不会休眠吗？ 如果是， 我会点python, 初步想法是python+selenium+firefox headless来登录。c9要下线？ 我收到AWS的邮件只是发个调查为什么没有搬迁到AWS去
额，翻墙已经不是目的，确实没啥，折腾这个过程才是目的，哈哈

**Comment by xuiv** [comment]
我试过chrome
headless，不好用，它不会直打开网页，如果你会用selenium操作的话是可行的，vnc和headless打开c9内存占用是一样的，都是400M，还有600M可以用来运行服务器，现在c9都可以开1G内存5G存储，够用了。condanywhere可以装vnc永不休眠：
http://xuiv-xuiv.codeanyapp.com/

在 2018年5月6日 下午8:46，c21xdx <notifications@github.com>写道：

**Comment by c21xdx** [comment]
大佬，为什么使用novnc就会被视为有活动而不休眠啊？用cronjob不停去呼novnc的url?
红帽旗下的codenvy.com可以用3G内存，和ssh登录,10分钟休眠。我试试怎么搞这个novnc让它不休眠

**Comment by xuiv** [comment]
codenvy不要试了，那个没有意义，它的虚拟机过十分钟强制关机，不论你如何操作。

**Comment by xuiv** [comment]
c9和codeanywhere只要你开webIDE，它就不会休眠，它们的webIDE并不在虚拟机内运行，所以可以在虚拟机内开启浏览器打开对应的IDE，这样就可以不休眠了。novnc只是一个网页版的vnc客户端，它用websockit通信，tightvncserver是事实上的X服务器和vnc服务器，需要websockify把tightvncserver的tcp端口封装成websocket端口。

**Comment by c21xdx** [comment]
大佬，C9你开什么项目可以开1G内存5G存储？我开空白都是512M和2G

**Comment by xuiv** [comment]
任意项目都可以修改为1G+5G，更高配置要收费

**Comment by xuiv** [comment]
大佬，应你的要求我做了一个，但是并未测试，我没用过v2ray，有问题请你自己改正吧。
https://github.com/xuiv/v2ray-heroku

**Comment by c21xdx** [comment]
学些大佬

**Comment by c21xdx** [comment]
大佬，这应该是你找的东西，https://github.com/cloudfoundry-community/ngrok-boshrelease。
ngrok你那里很快？我这里速度还不如直接ws呢
